version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/lrills/helm-unittest
    steps:
      - checkout
      - run:
          name: Create temp directory for coverage artifacts
          command: |
            mkdir -p /tmp/artifacts
      - run:
          name: Test include Codecoverage
          command: |
            go test -coverprofile=coverage -v ./unittest/...
            go tool cover -html=coverage -o coverage.html
            mv coverage.html /tmp/artifacts
      - run:
          name: Check formated
          command: "! gofmt -l . 2>&1 | read"
      - store_artifacts:
          path: /tmp/artifacts

  distribute:
    docker:
      - image: golang:1.14
    working_directory: /go/src/github.com/lrills/helm-unittest
    steps:
      - checkout
      - run:
          name: Insatll ghr
          command: go get -u github.com/tcnksm/ghr
      - run:
          name: Build binaries
          command: make dist
      - run:
          name: Upload binaries
          command: ghr -u $CIRCLE_USERNAME $CIRCLE_TAG _dist

workflows:
  version: 2
  test-and-build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - distribute:
          requires:
            - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)?/
            branches:
              ignore: /.*/
