name: go tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  full-test:
    name: full sdk and tools test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # tests for target OS
        os: [ubuntu-latest, macos-latest]
        # tests for actively maintained Go versions.
        go-version:
          - 1.21.x
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: test
      shell: bash
      run: make unittest